### ISSUE TITLE
[建议] 建议完成登陆后换个方式验证登陆是否成功

### ISSUE THREAD

**Issue by labulac** [hngyedu/EUserv_extend#2]
以这样的方式比较好，验证此处的xpath信息完成登陆验证，并通过再一次单击此处的xpath进入主机页面。
![image](https://user-images.githubusercontent.com/35835318/132205894-e8dbb079-d055-4ffe-b546-d35e1033a045.png)

因为有些账户的邮箱信息已经无法验证，因此干扰了信息判断

**Comment by hngyedu** [comment]
好的谢谢建议,可否一起开发这个项目,我的精力有限的😁
